### PR TITLE
Sample application with authentication endpoint, api endpoint, and simple user interface.

### PR DESCRIPTION
**Pull request by urnicus**
### Purpose
* This is a sample application utilizing the provided seed data and directions.
* Please see the readme for installation instructions.

### Features
* Authentication endpoint returning a json web token if a user successfully logins.
* Api endpoint confirming the user is authenticated with their jwt and advising if it is raining in a users location.
* Vue frontend handling the above login requests and raining check
* Please see the readme for installation

### Testing
* Rspec and Simplecov
`211 / 211 LOC (100.0%) covered`

### CODE REVIEW

**Comment by ziplokk1** [comment]
Give me a bit to review this one. Sorry I'm just getting to this. Have you sent over an email to us?

**Review by ziplokk1 — CHANGES_REQUESTED** [review]
Please remove jetbrains config from the PR.

**Comment by urnicus** [comment]
> Give me a bit to review this one. Sorry I'm just getting to this. Have you sent over an email to us?

I've am in contact with Bret - he asked me to submit a PR here.  He confirmed my email a couple of days ago that he was aware of its existence.  I'll get the config removed and confirm.  Thanks!

**Comment by ziplokk1** [comment]
Awesome! I've been heads down with work lately and hadn't had a chance to talk with Bret. I'll reach out to him Monday.

**Comment by urnicus** [comment]
Work???  Haha, no worries.  I always forget to clear the cache after adding intelliJ config to gitignore.  

This does require a master.key.  I sent it over to Bret and you are welcome to grab from him.  I shot it over to your email listed on your profile.  Please, take a look at it on Monday after you've had a chance to catch up with him and have a great weekend!

**Pull request closed without merging**
